### ISSUE TITLE
unity_simulator.comm_unity.UnityCommunicationException: HTTPConnectionPool(host='127.0.0.1', port=6314): Read timed out

### ISSUE THREAD

**Issue by zhangliyun9120** [UMass-Foundation-Model/Co-LLM-Agents#1]
I got this error when I run ./scripts/symbolic_obs_llm_llm.sh and and python vh_demo.py --deployment local --extra_agent LLM_comm --task_group 0 --showmodal in envs/cwah: 

(cwah) liyun@DESKTOP-0NAM80S:~/Co-LLM-Agents/envs/cwah$ ./scripts/symbolic_obs_llm_llm.sh
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Init Env
['/home/liyun/Co-LLM-Agents/envs/cwah/../executable/linux_exec.v2.3.0.x86_64', '-batchmode', '-nographics', '-http-port=6314', '-logFile /home/liyun/Co-LLM-Agents/envs/cwah/Player_6314.log']
Getting connection...
error: XDG_RUNTIME_DIR not set in the environment.
episode: 0
task_goal:  {0: {'on_pudding_268': 1, 'on_juice_268': 1, 'on_apple_268': 1, 'on_cupcake_268': 2}, 1: {'on_pudding_268': 1, 'on_juice_268': 1, 'on_apple_268': 1, 'on_cupcake_268': 2}}
total_goal:  {'on_pudding_268': 2, 'on_juice_268': 2, 'on_apple_268': 2, 'on_cupcake_268': 2}
Resetting... Envid: 3. Taskid: 0. Index: 0
Traceback (most recent call last):
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=6314): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liyun/Co-LLM-Agents/envs/cwah/envs/../../virtualhome/simulation/unity_simulator/comm_unity.py", line 92, in post_command
    resp = requests.post(self._address, json=request_dict, timeout=self.timeout_wait)
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/liyun/anaconda3/envs/cwah/lib/python3.8/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=6314): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testing_agents/test_symbolic_LLMs.py", line 116, in <module>
    arena.reset(episode_id)
  File "/home/liyun/Co-LLM-Agents/envs/cwah/testing_agents/../algos/arena_mp2.py", line 53, in reset
    ob = self.env.reset(task_id=task_id)
  File "/home/liyun/Co-LLM-Agents/envs/cwah/testing_agents/../envs/unity_environment.py", line 325, in reset
    s, g = self.comm.environment_graph()
  File "/home/liyun/Co-LLM-Agents/envs/cwah/envs/../../virtualhome/simulation/unity_simulator/comm_unity.py", line 298, in environment_graph
    response = self.post_command({'id': str(time.time()), 'action': 'environment_graph'})
  File "/home/liyun/Co-LLM-Agents/envs/cwah/envs/../../virtualhome/simulation/unity_simulator/comm_unity.py", line 98, in post_command
    raise UnityCommunicationException(str(e))
unity_simulator.comm_unity.UnityCommunicationException: HTTPConnectionPool(host='127.0.0.1', port=6314): Read timed out. (read timeout=30)
CLOSING PROC
CLOSING PROC
CLOSING PROC

Could you please hlep me to hanle with this ASAP? it seems the v2.3.0 virtualhome_unity problem refer to this https://github.com/xavierpuigf/virtualhome/issues/42?

**Comment by zhangliyun9120** [comment]
> 



> Hi, @zhangliyun9120 I think your issue occurs here:
> 
> ```
> error: XDG_RUNTIME_DIR not set in the environment.
> ```
> 
> It seems that your environment is missing some environment variables, and you can set the environment variable by yourself:
> 
> ```
> export XDG_RUNTIME_DIR=/run/user/$(id -u)
> ```
> 
> In my env, it is set to "/run/user/1937".

Thank you for your reply, previously I used a WSL-Ubuntu20.04 environment to run, it seems to have some environment setup problem. 
Now I have already changed to Win11 environment, torch-1.11.0, cuda-11.5, but I still got the error:

(cwah) PS D:\Co-LLM-Agents\envs\cwah\virtualhome_userinterface> python vh_demo.py --deployment remote --task_group 0 --showmodal
[0]
args.task_group [0]
task_index_shuffle [0]
task_index 0
args.task_group [0]
CLOSING PROC
Traceback (most recent call last):
  File "vh_demo.py", line 980, in <module>
    reset(None)
  File "vh_demo.py", line 739, in reset
    env = UnityEnvironment(**envarg)
  File "D:\Co-LLM-Agents\envs\cwah\virtualhome_userinterface\..\envs\unity_environment.py", line 48, in __init__
    super(UnityEnvironment, self).__init__(
  File "D:\Co-LLM-Agents\envs\cwah\virtualhome_userinterface\..\..\virtualhome\simulation\environment\unity_environment.py", line 100, in __init__
    self.comm = comm_unity.UnityCommunication(port=str(self.port_number), **self.executable_args)
  File "D:\Co-LLM-Agents\envs\cwah\virtualhome_userinterface\..\..\virtualhome\simulation\unity_simulator\comm_unity.py", line 44, in __init__
    self.launcher = communication.UnityLauncher(port=port, file_name=file_name, x_display=x_display,
  File "D:\Co-LLM-Agents\envs\cwah\virtualhome_userinterface\..\..\virtualhome\simulation\unity_simulator\communication.py", line 15, in __init__
    self.launch_executable(file_name, x_display=x_display, no_graphics=no_graphics, logging=logging, docker_enabled=docker_enabled)
  File "D:\Co-LLM-Agents\envs\cwah\virtualhome_userinterface\..\..\virtualhome\simulation\unity_simulator\communication.py", line 156, in launch_executable
    raise Exception(
Exception: Couldn't launch the linux_exec.v2.3.0 environment. Provided filename does not match any environments.
CLOSING PROC

Then I found the ../../executable/linux_exec.v2.3.0.x86_64 file you provided is Linux version, and I tried to downloaded a same Windows version simulator ..\..\windows_exec.v2.3.0\VirtualHome.exe, but it seems that it cannot work well.

So can I just use windows environment to implement your work?

**Comment by StigLidu** [comment]
Using Linux to build the environment is better since we do not test this repo in Windows, so some potential env conflicts might happen when using Windows.

Regarding your question, you need to specify the location of the executable file when using Windows, which can be done by adding ``--executable_file {PATH_TO_EXECUTABLE_FILE}``.

**Comment by zhangliyun9120** [comment]
> Using Linux to build the environment is better since we do not test this repo in Windows, so some potential env conflicts might happen when using Windows.
> 
> Regarding your question, you need to specify the location of the executable file when using Windows, which can be done by adding `--executable_file {PATH_TO_EXECUTABLE_FILE}`.

**I tried but it still failed. What is the expected result of cwah can you describe that?** 

**Also, when I tried tdw_mat by ./scripts/test_LMs.sh I also got the error:**
You are using TDW 1.11.18.0 but version 1.12.0.0 is available.
To upgrade to the last version of 1.11:
pip3 install tdw==1.11.23.5
Consider upgrading to the latest version of TDW (1.12.0):
pip3 install tdw -U
Build version 1.11.18
Unity Engine 2020.3.24f1
Python tdw module version 1.11.18
{'scene': '5a', 'layout': '0_0', 'seed': 2824, 'task': 'food'}
New Setting: True
close
Traceback (most recent call last):
  File "/home/liyun/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 174, in <module>
    main()
  File "/home/liyun/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 169, in main
    challenge.submit(agents, logger, args.eval_episodes)
  File "/home/liyun/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 56, in submit
    state, info, env_api = self.env.reset(seed=self.data[i]['seed'], options=self.data[i], output_dir = os.path.join(self.output_dir, str(i)))
  File "/home/liyun/miniconda3/envs/tdw_mat/lib/python3.9/site-packages/gym/wrappers/order_enforcing.py", line 42, in reset
    return self.env.reset(**kwargs)
  File "/home/liyun/miniconda3/envs/tdw_mat/lib/python3.9/site-packages/gym/wrappers/env_checker.py", line 45, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/home/liyun/miniconda3/envs/tdw_mat/lib/python3.9/site-packages/gym/utils/passive_env_checker.py", line 192, in env_reset_passive_checker
    result = env.reset(**kwargs)
  File "/home/liyun/Co-LLM-Agents/envs/tdw_mat/tdw-gym/tdw_gym.py", line 184, in reset
    self.controller.start_floorplan_trial(scene=scene, layout=layout, replicants=self.number_of_agents, num_containers=4, num_target_objects=10,
  File "/home/liyun/Co-LLM-Agents/envs/tdw_mat/transport_challenge_multi_agent/transport_challenge.py", line 169, in start_floorplan_trial
    self._start_trial_new(replicants=replicants, task_type = task, random_seed=random_seed)
  File "/home/liyun/Co-LLM-Agents/envs/tdw_mat/transport_challenge_multi_agent/transport_challenge.py", line 309, in _start_trial_new
    self.communicate([])
  File "/home/liyun/Co-LLM-Agents/envs/tdw_mat/transport_challenge_multi_agent/transport_challenge.py", line 202, in communicate
    return super().communicate(commands)
  File "/home/liyun/miniconda3/envs/tdw_mat/lib/python3.9/site-packages/tdw/controller.py", line 159, in communicate
    m.on_send(resp=resp)
  File "/home/liyun/miniconda3/envs/tdw_mat/lib/python3.9/site-packages/tdw/add_ons/replicant.py", line 158, in on_send
    self._set_dynamic_data(resp=resp)
  File "/home/liyun/miniconda3/envs/tdw_mat/lib/python3.9/site-packages/tdw/add_ons/replicant.py", line 559, in _set_dynamic_data
    self.dynamic = ReplicantDynamic(resp=resp, replicant_id=self.replicant_id, frame_count=self._frame_count)
  File "/home/liyun/miniconda3/envs/tdw_mat/lib/python3.9/site-packages/tdw/replicant/replicant_dynamic.py", line 117, in __init__
    image_data = TDWUtils.get_shaped_depth_pass(images=images, index=j)
  File "/home/liyun/miniconda3/envs/tdw_mat/lib/python3.9/site-packages/tdw/tdw_utils.py", line 307, in get_shaped_depth_pass
    return np.flip(np.reshape(images.get_image(index), (images.get_height(), images.get_width(), 3)), 0)
  File "<__array_function__ internals>", line 200, in reshape
  File "/home/liyun/miniconda3/envs/tdw_mat/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/liyun/miniconda3/envs/tdw_mat/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 196608 into shape (1047,1908,3)
kill: (82101): No such process

**How to resolve these?
Hope to get your reply ASAP. Thanks a lot.**

**Comment by likelimulu** [comment]
My Linux also has this problem, which still fails after manually setting: export XDG_RUNTIME_DIR=/run/user/$(id -u)

![d1626145034eeb6bf230fb728e39b65](https://github.com/UMass-Foundation-Model/Co-LLM-Agents/assets/78798677/d365f8b2-5693-47b5-b619-aedde9b489ac)

Maybe it's because there is no GUI installed in my system? 

Look forward to your reply. Thank you so much!

**Comment by zhangliyun9120** [comment]
> My Linux also has this problem, which still fails after manually setting: export XDG_RUNTIME_DIR=/run/user/$(id -u)
> 
> ![d1626145034eeb6bf230fb728e39b65](https://user-images.githubusercontent.com/78798677/255380750-d365f8b2-5693-47b5-b619-aedde9b489ac.png)
> 
> Maybe it's because there is no GUI installed in my system?
> 
> Look forward to your reply. Thank you so much!

I don't think it is main problem, I run this in pure ubuntu, it still cannot work well. I have already given up. I think the code have problems.@likelimulu @StigLidu please give a reply asap, thanks

**Comment by Icefoxzhx** [comment]
This issue may be caused by a version conflict with the VirtualHome executable. 
We have provided the new version [here](https://drive.google.com/file/d/1JTrV5jdF-LQVwY3OsV3Jd3r6PRghyHBp/view?usp=sharing) and updated the readme.
Hope it helps.
