### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'target'

### ISSUE THREAD

**Issue by 311706029** [UMass-Foundation-Model/Co-LLM-Agents#19]
After executing `./scripts/test_LM.sh`, the following TypeError occurs when the agent is asked to place an target_object into a container.

Traceback (most recent call last):
  File "/home/eclab/Desktop/compete-llm/compete-LLM-Agents/tdw_mat/tdw-gym/challenge.py", line 185, in <module>
    main()
  File "/home/eclab/Desktop/compete-llm/compete-LLM-Agents/tdw_mat/tdw-gym/challenge.py", line 179, in main
    challenge.submit(agents, logger, args.eval_episodes)
  File "/home/eclab/Desktop/compete-llm/compete-LLM-Agents/tdw_mat/tdw-gym/challenge.py", line 82, in submit
    state, reward, done, info = self.env.step(actions)
  File "/home/eclab/anaconda3/envs/tdw_mat/lib/python3.9/site-packages/gym/wrappers/order_enforcing.py", line 37, in step
    return self.env.step(action)
  File "/home/eclab/anaconda3/envs/tdw_mat/lib/python3.9/site-packages/gym/wrappers/env_checker.py", line 39, in step
    return self.env.step(action)
  File "/home/eclab/Desktop/compete-llm/compete-LLM-Agents/tdw_mat/tdw-gym/tdw_gym.py", line 697, in step
    data = self.controller.communicate([])
  File "/home/eclab/Desktop/compete-llm/compete-LLM-Agents/tdw_mat/transport_challenge_multi_agent/transport_challenge.py", line 202, in communicate
    return super().communicate(commands)
  File "/home/eclab/Desktop/compete-llm/compete-LLM-Agents/tdw_mat/transport_challenge_multi_agent/asset_cached_controller.py", line 46, in communicate
    m.on_send(resp)
  File "/home/eclab/anaconda3/envs/tdw_mat/lib/python3.9/site-packages/tdw/add_ons/replicant.py", line 170, in on_send
    initialization_commands = self.action.get_initialization_commands(resp=resp,
  File "/home/eclab/Desktop/compete-llm/compete-LLM-Agents/tdw_mat/transport_challenge_multi_agent/put_in.py", line 96, in get_initialization_commands
    return self._move_object_arm_away(resp=resp, static=static, dynamic=dynamic)
  File "/home/eclab/Desktop/compete-llm/compete-LLM-Agents/tdw_mat/transport_challenge_multi_agent/put_in.py", line 166, in _move_object_arm_away
    self._sub_action = ReachForTransportChallenge(target={k: v for k, v in target.items()}, 
  File "/home/eclab/Desktop/compete-llm/compete-LLM-Agents/tdw_mat/transport_challenge_multi_agent/reach_for_transport_challenge.py", line 25, in __init__
    super().__init__(target=target,
TypeError: __init__() got an unexpected keyword argument 'target'

**Comment by Icefoxzhx** [comment]
Which tdw version are you using?
It's recommended to use the same version as in tdw_mat/requirements.txt   tdw==1.11.23.5
With a different version, there may be conflicts regarding replicants' actions.

**Comment by 311706029** [comment]
Following are the output after executing `python demo/demo_scene.py`
Which is the same version as the requirements.txt but still have the TypeError

You are using TDW 1.11.23.5 but version 1.12.24.1 is available.
Consider upgrading to the latest version of TDW (1.12.24):
pip3 install tdw -U
Build version 1.11.23
Unity Engine 2020.3.24f1
Python tdw module version 1.11.23
{<Arm.left: 0>: 13013409, <Arm.right: 1>: 6753020}
[13013409]
[6753020, 2540002, 11266758, 8676814, 4546869, 3843252]
Arm.left Arm.right
Traceback (most recent call last):
  File "/home/eclab/projects/hermit/collm/Co-LLM-Agents(base1)/tdw_mat/demo/demo_scene.py", line 147, in <module>
    data = c.communicate([])
  File "/home/eclab/anaconda3/envs/tdw_mat/lib/python3.9/site-packages/tdw/controller.py", line 160, in communicate
    m.on_send(resp=resp)
  File "/home/eclab/anaconda3/envs/tdw_mat/lib/python3.9/site-packages/tdw/add_ons/replicant.py", line 170, in on_send
    initialization_commands = self.action.get_initialization_commands(resp=resp,
  File "/home/eclab/projects/hermit/collm/Co-LLM-Agents(base1)/tdw_mat/transport_challenge_multi_agent/put_in.py", line 94, in get_initialization_commands
    return self._move_object_arm_away(resp=resp, static=static, dynamic=dynamic)
  File "/home/eclab/projects/hermit/collm/Co-LLM-Agents(base1)/tdw_mat/transport_challenge_multi_agent/put_in.py", line 158, in _move_object_arm_away
    self._sub_action = ReachForTransportChallenge(target={k: v for k, v in target.items()},
  File "/home/eclab/projects/hermit/collm/Co-LLM-Agents(base1)/tdw_mat/transport_challenge_multi_agent/reach_for_transport_challenge.py", line 25, in __init__
    super().__init__(target=target,
TypeError: __init__() got an unexpected keyword argument 'target'

**Comment by bluehyena** [comment]
I'm experiencing the same error in tdw==1.11.23.5

You are using TDW 1.11.23.5 but version 1.12.24.2 is available.
Consider upgrading to the latest version of TDW (1.12.24):
pip3 install tdw -U
Build version 1.11.23
Unity Engine 2020.3.24f1
Python tdw module version 1.11.23
{<Arm.left: 0>: 6884406, <Arm.right: 1>: 7100798}
[6884406]
[7100798, 4938454, 16761474, 2307674, 6251514, 8346748]
Arm.left Arm.right
Traceback (most recent call last):
  File "/data/LeeJH/Co-LLM-Agents/tdw_mat/demo/demo_scene.py", line 147, in <module>
    data = c.communicate([])
  File "/home/guest1/miniconda3/envs/tdw_mat/lib/python3.9/site-packages/tdw/controller.py", line 160, in communicate
    m.on_send(resp=resp)
  File "/home/guest1/miniconda3/envs/tdw_mat/lib/python3.9/site-packages/tdw/add_ons/replicant.py", line 170, in on_send
    initialization_commands = self.action.get_initialization_commands(resp=resp,
  File "/data/LeeJH/Co-LLM-Agents/tdw_mat/transport_challenge_multi_agent/put_in.py", line 94, in get_initialization_commands
    return self._move_object_arm_away(resp=resp, static=static, dynamic=dynamic)
  File "/data/LeeJH/Co-LLM-Agents/tdw_mat/transport_challenge_multi_agent/put_in.py", line 158, in _move_object_arm_away
    self._sub_action = ReachForTransportChallenge(target={k: v for k, v in target.items()},
  File "/data/LeeJH/Co-LLM-Agents/tdw_mat/transport_challenge_multi_agent/reach_for_transport_challenge.py", line 25, in __init__
    super().__init__(target=target,
TypeError: __init__() got an unexpected keyword argument 'target'

**Comment by ssw03270** [comment]
tdw_mat/transport_challenge_multi_agent/reach_for_transport_challenge.py
line 25,

`super().__init__(targets=[target],`

**Comment by jliu4ai** [comment]
Does this issue also lead to that sometimes the agents goes through the wall and stay out of the all homes?

**Comment by hugyu** [comment]
> tdw_mat/transport_challenge_multi_agent/reach_for_transport_challenge.py line 25,
> 
> `super().__init__(targets=[target],`

Thank you for your answer. I would like to ask how long demo_scene.py takes to run

**Comment by ssw03270** [comment]
> > tdw_mat/transport_challenge_multi_agent/reach_for_transport_challenge.py line 25,
> > `super().__init__(targets=[target],`
> 
> Thank you for your answer. I would like to ask how long demo_scene.py takes to run

The program took about 1 minute to execute

**Comment by StigLidu** [comment]
Thank you all for your contributions and patience with this issue.

The problem arose due to an update in the TDW environment in version 1.11.20, where the parameter name was changed from `target` to `targets`.

We have addressed this bug in the latest commit by changing `target` to `targets`.
