### ISSUE TITLE
Provided filename does not match any environments. CLOSING PROC

### ISSUE THREAD

**Issue by MubasharSaeedPhD** [UMass-Foundation-Model/Co-LLM-Agents#32]
./scripts/symbolic_obs_llm_llm.sh
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Init Env
CLOSING PROC
Traceback (most recent call last):
  File "testing_agents/test_symbolic_LLMs.py", line 76, in <module>
    arena = ArenaMP(args.max_episode_length, id_run, env_fn, agents, args.record_dir, args.debug)
  File "/home/mubashar/COLLm/Co-LLM-Agents/cwah/testing_agents/../algos/arena_mp2.py", line 28, in __init__
    self.env = environment_fn(arena_id)
  File "testing_agents/test_symbolic_LLMs.py", line 54, in env_fn
    return UnityEnvironment(num_agents=2,
  File "/home/mubashar/COLLm/Co-LLM-Agents/cwah/testing_agents/../envs/unity_environment.py", line 48, in __init__
    super(UnityEnvironment, self).__init__(
  File "/home/mubashar/COLLm/Co-LLM-Agents/cwah/envs/../../virtualhome/simulation/environment/unity_environment.py", line 100, in __init__
    self.comm = comm_unity.UnityCommunication(port=str(self.port_number), **self.executable_args)
  File "/home/mubashar/COLLm/Co-LLM-Agents/cwah/envs/../../virtualhome/simulation/unity_simulator/comm_unity.py", line 44, in __init__
    self.launcher = communication.UnityLauncher(port=port, file_name=file_name, x_display=x_display,
  File "/home/mubashar/COLLm/Co-LLM-Agents/cwah/envs/../../virtualhome/simulation/unity_simulator/communication.py", line 15, in __init__
    self.launch_executable(file_name, x_display=x_display, no_graphics=no_graphics, logging=logging, docker_enabled=docker_enabled)
  File "/home/mubashar/COLLm/Co-LLM-Agents/cwah/envs/../../virtualhome/simulation/unity_simulator/communication.py", line 156, in launch_executable
    raise Exception(
Exception: Couldn't launch the linux_exec.v2.3.0 environment. Provided filename does not match any environments.
CLOSING PROC

**Comment by StigLidu** [comment]
The executable may not be in the correct directory or doesn't have the proper permissions to run. Please ensure that the folder structure is as follows:
```
|--cwah/
|--virtualhome/
|--executable/
    |--linux_exec.v2.3.0.x86_64
    |--linux_exec.v2.3.0_Data
    ...
```
Meanwhile, check whether `linux_exec.v2.3.0.x86_64` is permitted to launch:
```bash
chmod +x executable/linux_exec.v2.3.0.x86_64
```
