### ISSUE TITLE
Logging error after run `scripts/test_LMs.sh`.

### ISSUE THREAD

**Issue by yushengsu-thu** [UMass-Foundation-Model/Co-LLM-Agents#4]
Hello,
I have a question about the "Logging error". After I launch the `scripts/test_LMs.sh`, the system shows this error but the code still keep runing. Is it normal? (I use mac os).

Python tdw module version 1.11.18
{'scene': '5a', 'layout': '0_0', 'seed': 2824, 'task': 'food'}
New Setting: True
dataset/dataset_test/5a_0_0_metadata.json saved
/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:199: UserWarning: WARN: The result returned by `env.reset()` should be `(obs, info)` by default, , where `obs` is a observation and `info` is a dictionary containing additional information.
  logger.warn(
--- Logging error ---
Traceback (most recent call last):
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 177, in <module>
    main()
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 172, in main
    challenge.submit(agents, logger, args.eval_episodes)
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 64, in submit
    agent.reset(obs = state[str(id)], goal_objects = info['goal_description'], output_dir = os.path.join(self.output_dir, str(i)), env_api = env_api, rooms_name=info['rooms_name'])
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/lm_agent.py", line 395, in reset
    self.logger.info(self.goal_objects, goal_count)
Message: {'orange': 2, 'apple': 3, 'banana': 1, 'bread': 3, 'burger': 1}
Arguments: (10,)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 177, in <module>
    main()
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 172, in main
    challenge.submit(agents, logger, args.eval_episodes)
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 64, in submit
    agent.reset(obs = state[str(id)], goal_objects = info['goal_description'], output_dir = os.path.join(self.output_dir, str(i)), env_api = env_api, rooms_name=info['rooms_name'])
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/lm_agent.py", line 395, in reset
    self.logger.info(self.goal_objects, goal_count)
Message: {'orange': 2, 'apple': 3, 'banana': 1, 'bread': 3, 'burger': 1}
Arguments: (10,)
dict_keys(['visible_objects', 'rgb', 'seg_mask', 'depth', 'camera_matrix', 'agent', 'held_objects', 'oppo_held_objects', 'FOV', 'status', 'messages', 'valid', 'current_frames'])
['<Livingroom> (1000)', '<Bedroom> (2000)', '<Office> (3000)', '<Livingroom> (4000)', '<Kitchen> (5000)', '<Livingroom> (6000)']
--- Logging error ---
Traceback (most recent call last):
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 177, in <module>
    main()
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 172, in main
    challenge.submit(agents, logger, args.eval_episodes)
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 64, in submit
    agent.reset(obs = state[str(id)], goal_objects = info['goal_description'], output_dir = os.path.join(self.output_dir, str(i)), env_api = env_api, rooms_name=info['rooms_name'])
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/lm_agent.py", line 395, in reset
    self.logger.info(self.goal_objects, goal_count)
Message: {'orange': 2, 'apple': 3, 'banana': 1, 'bread': 3, 'burger': 1}
Arguments: (10,)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/Users/shengsu/Downloads/miniconda/envs/embodied/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 177, in <module>
    main()
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 172, in main
    challenge.submit(agents, logger, args.eval_episodes)
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/challenge.py", line 64, in submit
    agent.reset(obs = state[str(id)], goal_objects = info['goal_description'], output_dir = os.path.join(self.output_dir, str(i)), env_api = env_api, rooms_name=info['rooms_name'])
  File "/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/lm_agent.py", line 395, in reset
    self.logger.info(self.goal_objects, goal_count)
Message: {'orange': 2, 'apple': 3, 'banana': 1, 'bread': 3, 'burger': 1}
Arguments: (10,)
dict_keys(['visible_objects', 'rgb', 'seg_mask', 'depth', 'camera_matrix', 'agent', 'held_objects', 'oppo_held_objects', 'FOV', 'status', 'messages', 'valid', 'current_frames'])
['<Livingroom> (1000)', '<Bedroom> (2000)', '<Office> (3000)', '<Livingroom> (4000)', '<Kitchen> (5000)', '<Livingroom> (6000)']
/Users/shengsu/Downloads/embodied/Co-LLM-Agents/envs/tdw_mat/tdw-gym/tdw_gym.py:710: RuntimeWarning: divide by zero encountered in divide
  depth_img = Image.fromarray(100 / depth).convert('RGB')
2023-07-19 11:55:39,196 - simple_example - INFO - Environment Reset. Took 294.9135160446167 secs

**Comment by Icefoxzhx** [comment]
Hi! We updated most of the codebase these days, does this error still persist now?
